### ISSUE TITLE
8821c sees mainline support in rtw88

### ISSUE THREAD

**Issue by makson96** [tomaspinho/rtl8821ce#142]
Hi,
I just want to share with you great news, which I discovered. As of today initial support for rtl8821c was published for mainline kernel (in rtw88 driver). Here are kernel patches:
https://patchwork.kernel.org/patch/11559307/
https://patchwork.kernel.org/patch/11559297/
https://patchwork.kernel.org/patch/11559301/
https://patchwork.kernel.org/patch/11559299/
https://patchwork.kernel.org/patch/11559303/
https://patchwork.kernel.org/patch/11559295/
https://patchwork.kernel.org/patch/11559293/
And here is the firmware:
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=401bd6defb64ebbaf3b020f30f2ac3735d3a0c0f
Best regards and have fun!

**Comment by tomaspinho** [comment]
This is great news! I intend to archive this repository once the new rtw88 is available in a stable mainline release and proven to be working.

**Comment by ObserverOfTime** [comment]
I installed `linux-firmware-git` and applied the patches to v5.7-rc7 (after fixing some rejections) but the driver isn't working. Perhaps it depends on something else I'm missing. There's a [pull request](https://lkml.kernel.org/linux-wireless/20200525114828.7BF6CC433CA@smtp.codeaurora.org/) for v5.8 that adds support for 8723DE, but not 8821CE. Hopefully it'll be added later.

**Comment by makson96** [comment]
I will probably give it a try, when it will be merged to wireless-drivers-next tree:
https://git.kernel.org/pub/scm/linux/kernel/git/kvalo/wireless-drivers-next.git

**Comment by makson96** [comment]
There is already second version of initial patches:
https://patchwork.kernel.org/cover/11575267/
And five additional patches:
https://patchwork.kernel.org/cover/11575281/
From the message of those new patches:
"
After this set, the RTL8821CE device is supported by rtw88.
"
So hopefully it will be ready soon.

**Comment by ukbeast** [comment]
OpenSUSE has now included the firmware in TW
https://build.opensuse.org/package/rdiff/openSUSE:Factory/kernel-firmware?linkrev=base&rev=143
`/rtw8821c_fw.bin`

**Comment by ObserverOfTime** [comment]
I tried the new patches on v5.7 but there are some compilation errors so I'll keep waiting.

**Comment by makson96** [comment]
Another update to patches:
https://patchwork.kernel.org/cover/11585415/
https://patchwork.kernel.org/cover/11585439/

**Comment by userofryzen** [comment]
i was going to say the same.. jajaj

**Comment by lsvincent** [comment]
This says something about the code being ready.
[https://patchwork.kernel.org/patch/11585441/](https://patchwork.kernel.org/patch/11585441/)

**Comment by URemery** [comment]
Hi,

I found the repo mentionned by Larry Finger in the link of Isvincent :
[https://github.com/lwfinger/rtlwifi_new](https://github.com/lwfinger/rtlwifi_new)

As I understand, if you want to give it a try you should refer to the README file of the rtw88 branch. Also, check the repo issues, there's already a user (mentionned in the link of Isvincent) who's trying to build the driver and Larry helps him.

I think that this user did not succeded yet but somebody may have the courage to try

**Comment by URemery** [comment]
Hi,

I tried to build the driver from the repo I shared in my last post. No problem during the build but it throws some errors when loading it (see issue #603 of the repo). I will rebuild as soon as there improvements.

**Comment by buboleck** [comment]
Yes, it builds fine on Gentoo kernel 5.7.1 but does not work, loads with errors:

[    2.324824] rtw_8821ce 0000:01:00.0: enabling device (0000 -> 0003)
[    2.329142] rtw_8821ce 0000:01:00.0: Firmware version 24.5.0, H2C version 12
[    2.350506] rtw_8821ce 0000:01:00.0: rfe 4 isn't supported
[    2.350612] rtw_8821ce 0000:01:00.0: failed to setup chip efuse info
[    2.350615] rtw_8821ce 0000:01:00.0: failed to setup chip information

**Comment by ObserverOfTime** [comment]
8821CE is entirely broken on v5.8-rc1 since the aforementioned error occurs with both the rtlwifi_new repo and the kernel patches, and this repo doesn't even build.

**Comment by tomaspinho** [comment]
Release Candidates are _release candidates_ for a reason :)

Mind posting the build logs in a new issue?

**Comment by mthw0** [comment]
I have the DKMS build log: https://pastebin.com/raw/T5dkTJnf

**Comment by buboleck** [comment]
> Yes, it builds fine on Gentoo kernel 5.7.1 but does not work, loads with errors:
> 
> [ 2.324824] rtw_8821ce 0000:01:00.0: enabling device (0000 -> 0003)
> [ 2.329142] rtw_8821ce 0000:01:00.0: Firmware version 24.5.0, H2C version 12
> [ 2.350506] rtw_8821ce 0000:01:00.0: rfe 4 isn't supported
> [ 2.350612] rtw_8821ce 0000:01:00.0: failed to setup chip efuse info
> [ 2.350615] rtw_8821ce 0000:01:00.0: failed to setup chip information

Apparently mine is "rfe 4", whatever it means. I added it as suggested but it crashes during boot. I think I'll go with voiding the warranty of the laptop and just putting some half mini pci atheros card. This is the first hardware not working in main line linux I got in more than 7 years.

**Comment by URemery** [comment]
@buboleck You may want to create an issue in the [rtlwifi_new/rtw88](https://github.com/lwfinger/rtlwifi_new) repo. We had the same dmesg output concerning 'rfe 2' and it has been corrected.

The driver from this repo now builds correctly but crashes after loading because of null pointer dereference bugs, we are currently trying to patch this while waiting for realtek devs to properly initialize the 8821ce chip data.

**Comment by URemery** [comment]
Hi everybody,

I'm sending this message throug a rtl8821ce chip using the rtw88 driver of [the repo of L. Finger](https://github.com/lwfinger/rtlwifi_new) on a archlinux machine with kernel 5.7.3-arch1-1 !
It's hopefully the driver that will be shipped in kernel 5.8 (Realtek still has some work to do though).

If you want to give it a try :
- Clone the rtw88 branch of the repo
- make && sudo make install
- blacklist all other conflicting drivers (such as the one from this repo)
- reboot
This protocol is also in the README file of the rtw88 branch.

**Comment by mthw0** [comment]
The mentioned driver is working now, although it doesn't work any better than this one. For example it still takes several seconds (~25 since pressing something on the keyboard) after waking up from sleep to reconnect. Does anybody else have this issue too?

**Comment by buboleck** [comment]
I noticed when the network is configured to take IP address via DHCP it is slow to connect, it set to static IP connects immediately. BTW the same behavior is on MS. I also noticed another strange thing, if I set fixed IP address in the router DHCP the connection fails, both on linux and windows. Windows obtains the DNS hotsname etc but fails to set the IP address.

**Comment by tomaspinho** [comment]
@buboleck sounds like a router with a slow DHCP server

**Comment by buboleck** [comment]
@tomaspinho my other devices connect fine, this is new laptop I got 2-3 weeks ago. I even tested with old dlink router with dd-wrt still the same.

**Comment by mthw0** [comment]
Even on the same device in Windows it reconnects immediately, only in Linux it takes almost half a minute.

**Comment by URemery** [comment]
It's maybe slower on startup yes, and it seems that it has some trouble connecting to a low strength signal. But it's only an indev version with patches so it can't be as efficient as a release version.
Larry told that he will communicate with the realtek devs about the bugs we found so that they can properly finish the job.
He also said that this driver hasn't been merged in a kernel tree yet, but someone from linux.org told me that a driver will be merged in kernel 5.8. Anyway the mainline driver is on a good way.

**Comment by mthw0** [comment]
> He also said that this driver hasn't been merged in a kernel tree yet, but someone from linux.org told me that a driver will be merged in kernel 5.8. 

Can it be merged even if the RCs don't have it? I am running RC2 right now and I had to install the rtw88 driver manually.

**Comment by el-banto** [comment]
https://lore.kernel.org/linux-wireless/875zai6xfl.fsf@codeaurora.org/T/#u

**Comment by bsmith7581** [comment]
The rtw88 driver from @lwfinger's repo is not ready for mainstream use. In my case it works fine on Arch with 5 GHz wifi, but it provides poor connections for 2.4 GHz wifi. The rtl8821ce driver from @tomaspinho’s repo works fine for me on 2.4 GHz and 5 GHz.

**Comment by ObserverOfTime** [comment]
I suppose that will be fixed by the time it makes it into v5.9.

**Comment by ukbeast** [comment]
Would it be easily possible to use tomaspinho's driver over rtw88 once the
driver has become available?

**Comment by tomaspinho** [comment]
@ukbeast Yes, it will be. However, I will stop maintaining this `rtl8821ce` when `rtw88` is released as part of a stable release of kernel `5.8`.

**Comment by mthw0** [comment]
@tomaspinho You mean 5.9? 5.8 is to be released in a week and the RCs don't contain the driver yet or am I missing something here?

**Comment by lwfinger** [comment]
The code should be in 5.9. It will NOT be in 5.8.

Things reported here will not be fixed unless they are reported to the mailing list at linux-wireless@vger.kernel.org. I do not have one of these devices, thus I cannot report any deficiencies other than failure to build and problems in starting the device. Choosing not to report them to that mailing list, which is the official way to report problems, means that the Realtek developers will be unaware of the problem!

**Comment by el-banto** [comment]
Any idea how long before this gets backported to Ubuntu LTS?

I found this: 
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1885862

**Comment by tomaspinho** [comment]
Well, looks like I was too optimistic. Honestly had the idea they would include the driver as part of 5.8.

Will have to maintain it until 5.9 as I want to have a bridge version to let go of this repository in a responsible fashion.

**Comment by lwfinger** [comment]
@el-banto: That would be a question for Ubuntu.

**Comment by el-banto** [comment]
Alright, thanks. I appreciate the work going into this.

**Comment by Eskander** [comment]
Was the new driver included in yesterday's 5.9 RC1?
I don't know how to check without actually installing the kernel.

**Comment by buboleck** [comment]
> Was the new driver included in yesterday's 5.9 RC1?
> I don't know how to check without actually installing the kernel.

Yes it is included. You can check here:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/?id=v5.9-rc1&id2=v5.8&dt=2

**Comment by Funeoz** [comment]
> Any idea how long before this gets backported to Ubuntu LTS?
> 
> I found this: 
> https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1885862

The fix has been released today.

**Comment by ObserverOfTime** [comment]
I just tried 5.9 RC1 and I'm still getting the `rfe 2 isn't supported` error.
How do I go about reporting this to the mailing list? @lwfinger

**Comment by buboleck** [comment]
The bottom of the readme:

When you have problems where the driver builds and loads correctly, but fails to work, a GitHub issue is NOT the best place to report it. I have no idea of the internal workings of any of the chips, and the Realtek engineers who do will not read these issues. To reach them, send E-mail to linux-wireless@vger.kernel.org. Include a detailed description of any messages in the kernel logs and any steps that you have taken to analyze or fix the problem. If your description is not complete, you are unlikely to get any satisfaction.

**Comment by el-banto** [comment]
@ObserverOfTime afaik, it's a known issue and will be fixed but idk when.

**Comment by tomaspinho** [comment]
How's rtw88 on the latest 5.9-rc2?

**Comment by mthw0** [comment]
I would love to try it, but it doesn't even boot (yet).

**Comment by ObserverOfTime** [comment]
>How's rtw88 on the latest 5.9-rc2?

Still not working.

**Comment by ClassyLion** [comment]
Tried 5.9-rc3, does not work.

**Comment by ObserverOfTime** [comment]
What about `dmesg | grep rtw`?

**Comment by ClassyLion** [comment]
> What about `dmesg | grep rtw`?

`   10.575785] rtw_8821ce 0000:01:00.0: enabling device (0000 -> 0003)
[   10.665837] rtw_8821ce 0000:01:00.0: Firmware version 24.5.0, H2C version 12
[   10.684683] rtw_8821ce 0000:01:00.0: rfe 2 isn't supported
[   10.684796] rtw_8821ce 0000:01:00.0: failed to setup chip efuse info
[   10.684798] rtw_8821ce 0000:01:00.0: failed to setup chip information `

**Comment by ClassyLion** [comment]
> What about `dmesg | grep rtw`?
[   10.575785] rtw_8821ce 0000:01:00.0: enabling device (0000 -> 0003)
[   10.665837] rtw_8821ce 0000:01:00.0: Firmware version 24.5.0, H2C version 12
[   10.684683] rtw_8821ce 0000:01:00.0: rfe 2 isn't supported
[   10.684796] rtw_8821ce 0000:01:00.0: failed to setup chip efuse info
[   10.684798] rtw_8821ce 0000:01:00.0: failed to setup chip information

**Comment by buboleck** [comment]
Only rfe 1 chips are supported in the kernel driver, rfe 2 also works but needs manual edit. Mine is rfe 4 and not working properly with the rtw88. 

On September 2, 2020 9:57:06 PM GMT+03:00, "Māris Popēns" <notifications@github.com> wrote:
>> What about `dmesg | grep rtw`?
>
>[   10.575785] rtw_8821ce 0000:01:00.0: enabling device (0000 -> 0003)
>[   10.665837] rtw_8821ce 0000:01:00.0: Firmware version 24.5.0, H2C
>version 12
>[   10.684683] rtw_8821ce 0000:01:00.0: rfe 2 isn't supported
>[   10.684796] rtw_8821ce 0000:01:00.0: failed to setup chip efuse info
>[   10.684798] rtw_8821ce 0000:01:00.0: failed to setup chip
>information
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tomaspinho/rtl8821ce/issues/142#issuecomment-685933543

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by el-banto** [comment]
@buboleck How do you check which RFE chip you have?

**Comment by ClassyLion** [comment]
@buboleck what would be the manual edit for rfe 2? Have tried looking, but haven't found any information on it.

**Comment by userofryzen** [comment]
May be the site to test and try is the bug filled in bugzilla...

**Comment by buboleck** [comment]
Check the dmesg log, it says rfe 2 3 4 etc not supported or something, the driver from Larry Finger repo contains the rfe 2 3 4 etc. 

On September 2, 2020 10:11:05 PM GMT+03:00, Krishi Wali <notifications@github.com> wrote:
>@buboleck How do you check which RFE chip you have?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tomaspinho/rtl8821ce/issues/142#issuecomment-685940891

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ObserverOfTime** [comment]
> the driver from Larry Finger repo contains the rfe 2 3 4 etc.

I've patched the kernel using the changes in the repo but it's still not working, despite not reporting any errors.
I'll try disabling the kernel module and installing it from the repo out of tree and see if it works that way.

**Comment by buboleck** [comment]
Ok, what rfe is your chip? 4 works with very poor reception. 1 and 2 seems to work ok. 

On September 2, 2020 10:50:56 PM GMT+03:00, ObserverOfTime <notifications@github.com> wrote:
>> the driver from Larry Finger repo contains the rfe 2 3 4 etc.
>
>I've patched the kernel using the changes in the repo but it's still
>not working, despite not reporting any errors.
>I'll try disabling the kernel module and installing it from the repo
>out of tree and see if it works that way.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tomaspinho/rtl8821ce/issues/142#issuecomment-685960009

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ObserverOfTime** [comment]
It's RFE 2 and the wireless frequency is 2.4Ghz.

The out-of-tree RTW88 module isn't working either.
There's no apparent error in dmesg but I can't connect.

```
[   10.681357] rtw_core: loading out-of-tree module taints kernel.
[   10.683029] rtw_core: module verification failed: signature and/or required key missing - tainting kernel
[   10.714049] rtw_8821ce 0000:02:00.0: enabling device (0000 -> 0003)
[   10.715481] rtw_8821ce 0000:02:00.0: Firmware version 24.5.0, H2C version 12
[   10.746561] rtw_8821ce 0000:02:00.0 wlo1: renamed from wlan0
[   11.943373] rtw_8821ce 0000:02:00.0: start vif 40:5b:d8:c9:18:f7 on port 0
```

**Comment by buboleck** [comment]
Try close to the router, could be the same issue as mine, very low reception. 

On September 3, 2020 2:41:39 PM GMT+03:00, ObserverOfTime <notifications@github.com> wrote:
>It's RFE 2 and the wireless frequency is 2.4Ghz.
>
>The out-of-tree RTW88 module isn't working either.
>There's no apparent error in dmesg but I can't connect.
>
>```
>[   10.681357] rtw_core: loading out-of-tree module taints kernel.
>[   10.683029] rtw_core: module verification failed: signature and/or
>required key missing - tainting kernel
>[   10.714049] rtw_8821ce 0000:02:00.0: enabling device (0000 -> 0003)
>[   10.715481] rtw_8821ce 0000:02:00.0: Firmware version 24.5.0, H2C
>version 12
>[   10.746561] rtw_8821ce 0000:02:00.0 wlo1: renamed from wlan0
>[   11.943373] rtw_8821ce 0000:02:00.0: start vif 40:5b:d8:c9:18:f7 on
>port 0
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tomaspinho/rtl8821ce/issues/142#issuecomment-686431869

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ObserverOfTime** [comment]
You're right! It actually works close to the router.

**Comment by buboleck** [comment]
Maybe you should also report it to the developers at linux-wireless@vger.kernel.org

On September 3, 2020 3:08:39 PM GMT+03:00, ObserverOfTime <notifications@github.com> wrote:
>You're right! It actually works close to the router.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tomaspinho/rtl8821ce/issues/142#issuecomment-686444820

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lwfinger** [comment]
Although the driver in this repo does not report an error for rfe 2, I only changed the table that is read. I did not make any modifications to the rest of the driver, which is likely why you have weak performance.

Yes, you should report this to the Linux Wireless Mailing List. That is the only way such matters will ever be fixed!

**Comment by ObserverOfTime** [comment]
Apparently I can't report it…

```
<linux-wireless@vger.kernel.org>: host vger.kernel.org[23.128.96.18] said: 553
    5.7.1 Hello [178.21.23.139], for your MAIL FROM address
    <chronobserver@disroot.org> policy analysis reported: Your address is not
    liked source for email (in reply to MAIL FROM command)
```

**Comment by lwfinger** [comment]
You must send plain text mail. No fancy formatting.

A quote regarding this error: "People experience problems when for example ``From:'', ``Sender:'' and possible ``Reply-To:'' headers present different addresses."

You might also check http://vger.kernel.org/mxverify.html.

**Comment by ObserverOfTime** [comment]
It was plain text and only had a From header.

**Comment by lwfinger** [comment]
You will need to contact the mailing list. Try sending an e-mail to autoanswer@vger.kernel.org. See what happens then.

**Comment by ObserverOfTime** [comment]
I get the same response.

**Comment by el-banto** [comment]
What distro is everyone using for testing this on latest release candidates? I tried using rc3 on Ubuntu but in dmesg it says failed to load firmware. No errors about RFE type.

**Comment by lwfinger** [comment]
@el-banto: Install the firmware. There is a copy in this repo, otherwise get if from Linux-Firmware, or tell Ubuntu that it is missing.

@ObserverOfTime: Post the complete message (with full headers). Perhaps that will show the error in your E-mail configuration.

**Comment by ClassyLion** [comment]
Installed 5.9-rc4. dmesg | grep rtw error message has new information.

[   13.139662] rtw_8821ce 0000:01:00.0: enabling device (0000 -> 0003)
[   13.143560] rtw_8821ce 0000:01:00.0: Direct firmware load for rtw88/rtw8821c_fw.bin failed with error -2
[   13.143565] rtw_8821ce 0000:01:00.0: failed to request firmware
[   13.143571] rtw_8821ce 0000:01:00.0: failed to load firmware
[   13.143573] rtw_8821ce 0000:01:00.0: failed to setup chip efuse info
[   13.143574] rtw_8821ce 0000:01:00.0: failed to setup chip information
[   13.144353] rtw_8821ce: probe of 0000:01:00.0 failed with error -22

**Comment by ObserverOfTime** [comment]
Do you have the latest firmware?

**Comment by ClassyLion** [comment]
How to check it and  how is it possible to update it?

**Comment by lwfinger** [comment]
You can also get it from the git repo at git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git.

In that repo it has a size, date, and md5sum of 137896 May 18 09:30 rtw88/rtw8821c_fw.bin, fb0a5c9cb5615cd80e4a6361225b0897

On the other had, that file is in the rtw88 repo and would be installed on your system with a "make install".

**Comment by el-banto** [comment]
To install it I just put the bin file into /lib/firmware/rtw88
Seemed to work, as I was getting the RFE 2 error now, before just failed to load firmware.

**Comment by mthw0** [comment]
I've tried Linux 5.9-rc4 (built from source with changed config) and wifi (both 2,4 and 5Ghz) works correctly. I am on Arch Linux.

**Comment by ClassyLion** [comment]
> To install it I just put the bin file into /lib/firmware/rtw88
> Seemed to work, as I was getting the RFE 2 error now, before just failed to load firmware.

Same situation. After running a `make install` in the linux firmware newest version, RFE 2 error again.

**Comment by buboleck** [comment]
It is expected, no now changes in the driver, it suports rfe 0 and 1

On September 8, 2020 12:10:24 PM GMT+03:00, "Māris Popēns" <notifications@github.com> wrote:
>> To install it I just put the bin file into /lib/firmware/rtw88
>> Seemed to work, as I was getting the RFE 2 error now, before just
>failed to load firmware.
>
>Same situation. After running a `make install` in the linux firmware
>newest version, RFE 2 error again, on rc4
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tomaspinho/rtl8821ce/issues/142#issuecomment-688733851

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by buboleck** [comment]
The bottom of the readme:

When you have problems where the driver builds and loads correctly, but fails to work, a GitHub issue is NOT the best place to report it. I have no idea of the internal workings of any of the chips, and the Realtek engineers who do will not read these issues. To reach them, send E-mail to linux-wireless@vger.kernel.org. Include a detailed description of any messages in the kernel logs and any steps that you have taken to analyze or fix the problem. If your description is not complete, you are unlikely to get any satisfaction.

> > To install it I just put the bin file into /lib/firmware/rtw88
> > Seemed to work, as I was getting the RFE 2 error now, before just failed to load firmware.
> 
> Same situation. After running a `make install` in the linux firmware newest version, RFE 2 error again, on rc4

Report it to linux-wireless@vger.kernel.org

**Comment by lwfinger** [comment]
I have seen a report that Realtek did not think that RFE 2 versions of at least one of the chips had been released to the public. Unless you report these instances on the linux-wireless mailing list, that problem will never be fixed!

**Comment by dubhater** [comment]
Some people already emailed linux-wireless about RFE 2 and 4. Should more people chime in about those RFE types? Would that be helpful?

**Comment by ObserverOfTime** [comment]
Are they aware of the low reception or just the lack of support?

**Comment by buboleck** [comment]
> Are they aware of the low reception or just the lack of support?

I emailed them about both rfe4 and the low reception.

**Comment by ObserverOfTime** [comment]
v5.9 is now stable and there's still no support for RFE 2.

**Comment by buboleck** [comment]
> v5.9 is now stable and there's still no support for RFE 2.

Nor for RFE 4 in my case...

**Comment by lwfinger** [comment]
I do not recall any reports of RFE 4 on the linux-wireless mailing list. The RFE2 case for the RTL8821CE has been reported, Realtek has a fix, and will be posting it when verifications have been completed. As I stated on the ML, I will apply the patches here as soon as they are available.

**Comment by buboleck** [comment]
> I do not recall any reports of RFE 4 on the linux-wireless mailing list. The RFE2 case for the RTL8821CE has been reported, Realtek has a fix, and will be posting it when verifications have been completed. As I stated on the ML, I will apply the patches here as soon as they are available.

Ahh... I will email again.

**Comment by no-1-rtl8821ce-fan** [comment]
How do I check what RFE my card is and what kernel is this likely to be in (hoping for it to squeeze into fedora 34 or ubuntu 21.04)? Thanks!

**Comment by dubhater** [comment]
I guess the easiest way would be to boot some live media that has a 5.9 kernel, like the Arch Linux installer. If your card is not supported, the error message from the driver will tell you what RFE it is.

**Comment by MischievousTomato** [comment]
> > I do not recall any reports of RFE 4 on the linux-wireless mailing list. The RFE2 case for the RTL8821CE has been reported, Realtek has a fix, and will be posting it when verifications have been completed. As I stated on the ML, I will apply the patches here as soon as they are available.
> 
> Ahh... I will email again.

I found only 1 email regarding the rfe4 support, and it hasnt gotten any attention at all...

**Comment by buboleck** [comment]
Was it mine? I emailed several times but got no reply at all. 

On November 17, 2020 7:35:57 PM GMT+02:00, MischievousTomato <notifications@github.com> wrote:
>> > I do not recall any reports of RFE 4 on the linux-wireless mailing
>list. The RFE2 case for the RTL8821CE has been reported, Realtek has a
>fix, and will be posting it when verifications have been completed. As
>I stated on the ML, I will apply the patches here as soon as they are
>available.
>> 
>> Ahh... I will email again.
>
>I found only 1 email regarding the rfe4 support, and it hasnt gotten
>any attention at all...
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tomaspinho/rtl8821ce/issues/142#issuecomment-729086301

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MischievousTomato** [comment]
https://lore.kernel.org/linux-wireless/1A3B6524-C775-4ACB-BF99-CCD9F2700B06@abv.bg/ This is the latest one.
Also, we have the same laptop.

**Comment by no-1-rtl8821ce-fan** [comment]
Ok so apparently I have an RFE 2 according to the arch iso when it boots up

It says RFE 2 isn't supported is that normal lol.

This is for the kernel 5.9 driver btw not the FOSS driver here.

**Comment by dubhater** [comment]
Yes, it's not supported yet. Realtek programmers said they will send the patches for RFE 2 soon, after some quality checking.

**Comment by no-1-rtl8821ce-fan** [comment]
> 
> 
> Yes, it's not supported yet. Realtek programmers said they will send the patches for RFE 2 soon, after some quality checking.

Okay awesome ty for info 👍

**Comment by el-banto** [comment]
I wonder why it's taking so long. ETA was 3 weeks ago (if verification passed)

**Comment by lwfinger** [comment]
How fast could you do all the tests, while carrying on all other work?

**Comment by MischievousTomato** [comment]
I emailed them about rfe4 again, no response ;-;

**Comment by BigmenPixel0** [comment]
So far, this driver does not work on RTL8821CE ... Do you know when it will be fixed?

**Comment by no-1-rtl8821ce-fan** [comment]
> So far, this driver does not work on RTL8821CE ... Do you know when it will be fixed?

Apparently it does on some?

I just want them to make RFE 2 workkk

**Comment by lwfinger** [comment]
Realtek is working on it. Of course, if you want to debug the problem and suggest a fix, your contributions would be helpful.

**Comment by BigmenPixel0** [comment]
> Realtek is working on it. Of course, if you want to debug the problem and suggest a fix, your contributions would be helpful.

Is it known in which kernel the driver will work perfectly?

**Comment by BigmenPixel0** [comment]
> > So far, this driver does not work on RTL8821CE ... Do you know when it will be fixed?
> 
> Apparently it does on some?
> 
> I just want them to make RFE 2 workkk

rtw88_8821ce

**Comment by hwpfeil** [comment]
> This is great news! I intend to archive this repository once the new rtw88 is available in a stable mainline release and proven to be working.
"...proven to be working. At this time, in 5.10.2, the rtw88_8821ce driver is not working.  Eudev does not trigger and add a link in /sys/net/class for the 8821ce adapter. I still have to use a 5.4 kernel with this module in order to connect to the router (or use a 50' cat-6 cable). RFE 2 still does not work. I don't know why, they've been working on it since last summer.

**Comment by ClassyLion** [comment]
I wonder fi there is a way to track progress or some info about the progress... if there is such a possibility.

**Comment by sergiomb2** [comment]
Hi, 
I reported here: https://bugzilla.kernel.org/show_bug.cgi?id=210779
my wonder if we can list all ids that still doesn't wok .
my is PCIe Wireless Network Adapter [10ec:c821]

**Comment by ClassyLion** [comment]
What could be the reason it takes so long?

**Comment by el-banto** [comment]
> What could be the reason it takes so long?

RFE2 support is here, coming in 5.12

**Comment by lwfinger** [comment]
They needed to get approval from the BT group. If you are dependent on another group's approval, you know it can take a long time. I posted the fix within an hour after the Realtek people posted it at linux-wireless@vger.kernel.org. If that is not fast enough, then I will let you take over maintainership of the repo!

**Comment by Quetzalcohuatl** [comment]
Driver does not work for RTL8821CE me either.. any suggestion

**Comment by sergiomb2** [comment]
> Driver does not work for RTL8821CE me either.. any suggestion

Can you say what is id of your wireless please run `lspci -s $(lspci | grep RTL88 | cut -b -7) -nk`

**Comment by buboleck** [comment]
Any news on RFE 4 support?

**Comment by lwfinger** [comment]
I'm not the one to ask. That is a question for the maintainers at linux-wireless@vger.kernel.org. They may not know that any rfe4 units are in the field.

**Comment by dubhater** [comment]
Time to send them an email a week until someone replies? Maybe they didn't see the first two or three emails... somehow?

**Comment by flexibeast** [comment]
i'm another person facing the RFE 4 issue, via a new Asus D509DA laptop.

**Comment by buboleck** [comment]
> i'm another person facing the RFE 4 issue, via a new Asus D509DA laptop.
> 
> i've just sent an email to linux-wireless about it: https://marc.info/?l=linux-wireless&m=161968427506696&w=2

Please email to linux-wireless@vger.kernel.org, we are trying to get the developers attention on RFE4, my laptop is M509DA with RFE4 card.

**Comment by Lortegap** [comment]
Welcome to the club! I emailed them back in.... last year? No news...

**Comment by lwfinger** [comment]
@flexibeast I see your E-mail in the archives, but it never got to me, and perhaps not the Realtek developers.

I sent a private message to my contact at Realtek, and he said that he would contact the owner of the 8821ce driver. He also notified me that Taiwan had a national holiday, and that it might be a while before we had an answer.

Note: I do not think anyone pays attention to the kernel bugzilla. I do not.

**Comment by tomaspinho** [comment]
Who is the owner of the 8821ce repo? Or do you mean this repo, so that would be me? 😅

I've sent a few e-mails over to Realtek contacts that were active on the mailing list, none of them ever got back to me...

**Comment by lwfinger** [comment]
Not the owner of the repo. I meant the owner of the driver at Realtek. I do not know his name or E-mail address, but I do have one contact that is responsive. He considers me as his grandfather.

**Comment by sergiomb2** [comment]
Tomás, the kernel source tree, have one file with all maintainers [1]  in line 14468 [2] 

[1] 
https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/staging.git/tree/MAINTAINERS

https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/staging.git/tree/MAINTAINERS#n14468
[2] 
REALTEK WIRELESS DRIVER (rtw88)
M:	Yan-Hsuan Chuang <@xxxxxxx>
L:	linux-wireless@vger.kernel.org
S:	Maintained
F:	drivers/net/wireless/realtek/rtw88/

**Comment by neutr0nStar** [comment]
How to find which **RFE** version of WIFI card is my laptop running ? My laptop is HP 14s fr0012AU, it was released in October 2020. If someone has any idea, please let me know.

**Comment by sergiomb2** [comment]
please run `lspci -s $(lspci | grep RTL88 | cut -b -7) -nk`
with pci id you should be able to find RFE on internet

**Comment by Eskander** [comment]
@neutr0nStar To answer your question from #228 and for anyone wondering: although the built-in kernel module was introduced in 5.9, it only became stable and usable in my laptop in Linux 5.12 (currently using it on Arch).
Note that the kernel never complained about "RFE not being supported" on my machine so I assume I have neither 2 or 4.

You can try `sudo dmesg | grep rtw` while loading the `rtw88` module and if there's no mention of `rfe # isn't supported`, it should work correctly.

**Comment by dubhater** [comment]
How to find the RFE: run some live media with Linux 5.9 - 5.11. Either you will have wifi, in which case it's RFE 0, or you will get an error message in dmesg which tells you if it's RFE 2 or 4. Not Fedora

RFE 0, 2, and 4 can all have the same PCI ID. The rtw88_8821ce module in Linux 5.12 has support for RFE 0 and 2, but it only handles one PCI ID: 10ec:c821.

**Comment by neutr0nStar** [comment]
@Eskander But if the WIFI card was not supported in the first place, how did you install arch Linux ?

**Comment by flexibeast** [comment]
@neutr0nStar:

i don't know @Eskander's situation, but in general:

* Assuming Arch can be installed from an optical disc, then if the laptop has an optical drive, then an Arch ISO could be downloaded and burned via another device, and then used in the laptop.
* If the laptop has an Ethernet port (my new one doesn't, sadly), a wired connection can be used to do an install.
* If the laptop *doesn't* have an Ethernet port, a USB wifi adaptor can be used. That's what i had to do. Out of several USB wifi adaptors that people i know had, only one ended up working (though only on the 2.4G band, not 5G): "Realtek Semiconductor Corp. RTL8188CUS 802.11n", ID 0bda:8176.

**Comment by neutr0nStar** [comment]
@flexibeast Thank you for replying to my query, but unfortunately my laptop has neither CD drive nor ethernet port, to increase my problem further, the usb ports of my laptop are sol close that when I plug in the flash drive (it’s a thick on though) the other port is unusable. That’s the reason I am waiting for arch Linux with 5.12 in archiso. 😅

**Comment by flexibeast** [comment]
@neutr0nStar: Ah dang. Can you perhaps try to find a USB drive with a smaller form factor?

**Comment by neutr0nStar** [comment]
@flexibeast I don’t have one, I’ll have to buy one, I too was surprised to find HP doing such things. Is there a way in which I can apply some patch to archiso before burning it so as to make the driver work ?

**Comment by flexibeast** [comment]
@neutr0nStar: i don't know, i'm sorry; i'm not familiar with how practical binary patching is in these sort of cases.

**Comment by Eskander** [comment]
@neutr0nStar It's an old install (2 years or so) so I'm not entirely sure but I believe I used a wifi dongle (I have plenty lying around), my laptop also comes with an Ethernet port. Phone tethering and 4G dongles are another solution.

As for your specific case, here's an obligatory Read the Wiki: [Offline installation](https://wiki.archlinux.org/title/Offline_installation), or you can even [build your own archiso](https://wiki.archlinux.org/title/Archiso).

**Comment by jotoho** [comment]
> @Eskander But if the WIFI card was not supported in the first place, how did you install arch Linux ?

I installed arch by using my android smartphone with USB-Tethering to connect to wifi using the smartphone's antenna. 

(In short: Smartphone logged into wifi and smartphone provides its network access to laptop via USB)

**Comment by BigmenPixel0** [comment]
Does it work now?

**Comment by Danfro** [comment]
Hi everyone,

I am having trouble with my wifi on a hp laptop with Ubuntu 21.04. After upgrading to 21.04, there is simply no wifi adapter available.

The rtl8821ce-dkms driver is installed. Wifi was working with 20.04 and 20.10, so no hardware issue.

I tried to grab some values with the commands listed above:
kernel 5.12.0-0521200-generic
DeviceName: Realtek Wireless LAN + BT
Subsystem: 103c:831a
Kernel modules: rtw88_8821ce

If you need further detail please let me know.
I would be glad if you could help me getting wifi back working under 21.04.

**Comment by buboleck** [comment]
This driver works for me on Gentoo kernel 5.12.7, check if it is not interfering with the rtw88 in kernel driver. 

On June 17, 2021 11:40:45 PM GMT+03:00, Danfro ***@***.***> wrote:
>Hi everyone,
>
>I am having trouble with my wifi on a hp laptop with Ubuntu 21.04.
>After upgrading to 21.04, there is simply no wifi adapter available.
>
>The rtl8821ce-dkms driver is installed. Wifi was working with 20.04 and
>20.10, so no hardware issue.
>
>I tried to grab some values with the commands listed above:
>kernel 5.12.0-0521200-generic
>DeviceName: Realtek Wireless LAN + BT
>Subsystem: 103c:831a
>Kernel modules: rtw88_8821ce
>
>If you need further detail please let me know.
>I would be glad if you could help me getting wifi back working under
>21.04.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tomaspinho/rtl8821ce/issues/142#issuecomment-863549470

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lwfinger** [comment]
If you want to use this repo, you will need to blacklist rtw88-8822ce, That will keep the system from loading all the rtw88-* modules. Note that the ones here are rtw-* to be able to keep them straight. As for the dkms stuff, you will need to work that out yourself.

**Comment by BigmenPixel0** [comment]
wow, rtw88 driver for rtl8821ce working :)

**Comment by sergiomb2** [comment]
yeah , now with kernel 5.12 and kernel 5.13 works for me correctly https://bugzilla.kernel.org/show_bug.cgi?id=210779

**Comment by Lortegap** [comment]
Rfe4 doesnt work yet still :(

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by flexibeast** [comment]
> Rfe4 doesnt work yet still :( 

Nor for me (kernel 5.13.8). 

@Lortegap, might you be willing to follow this up on the linux-wireless list, by replying to [the email i posted](https://marc.info/?l=linux-wireless&m=161968427506696&w=2) and mentioning it's still not working for you? i could then post a confirmation that it's still not working for me either.

**Comment by jotoho** [comment]
@flexibeast Looking at your email, I think that I have the same laptop model you do (or at least extremely similar). (Asus D509DA-EJ097T according to label on bottom of device). Newest kernel provided by ArchLinux (5.13.9-arch1-1) still does not support the rtl8821ce chip in my laptop either. Still getting that RFE 4 not supported error in kernel log. Won't reply to your email (yet) since they seemed quite annoyed by it.

**Comment by archkatze** [comment]
rtw88 performs really bad on my machine, ping drops and crashes, ig ill stay using rtl8821ce

**Comment by tianheg** [comment]
rtw88 made my pc freezed, whenver I connected to wifi, I can't even use mouse and keyboard, then I have to reboot pc through pressing the power button.

PC details:

```sh
➜  ~ neofetch --off
archie@arch 
----------- 
OS: Arch Linux x86_64 
Host: HP Laptop 14s-cr0xxx 
Kernel: 5.13.12-arch1-1 
Uptime: 1 hour, 59 mins 
Packages: 1187 (pacman) 
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: Plasma 5.22.4 
WM: KWin 
Theme: Breeze Light [Plasma], Breeze [GTK2/3] 
Icons: breeze [Plasma], breeze [GTK2/3] 
Terminal: konsole 
Terminal Font: IBM Plex Mono 11 
CPU: Intel i5-8250U (4) @ 3.400GHz 
GPU: Intel UHD Graphics 620 
GPU: AMD ATI Radeon R7 M260/M265 / M340/M360 / M440/M445 / 530/535 / 620/625 Mobile 
Memory: 3684MiB / 23926MiB
```

**Comment by bnjw5jhyxn** [comment]
@tianheg The comment above by sergiomb2 links to an issue report on Bugzilla, where Flavio Grossi (who had the same issue as you) managed to resolve it by adding the line
```
options rtw88_pci disable_aspm=1
```
in any file in the directory `/etc/mobprobe.d/`. Does this suggestion fix your problem?

**Comment by lwfinger** [comment]
Be aware that this is not a bug in the rtw88 driver. In fact, rtw88 is exposing a bug in your BIOS. Disabling the ASPM is relaxing the driver's reliance on the BIOS being correct.

**Comment by tianheg** [comment]
thanks for you two guys @bnjw5jhyxn @lwfinger , I tried @bnjw5jhyxn's way, it works for me now. What I have done had been record here https://github.com/tianheg/blog/issues/147#issuecomment-905061881

**Comment by Areidz** [comment]
I tried @bnjw5jhyxn way but it still doesn't work. I get:

```
rtw_8821ce 0000:00:00.0: rfe 6 isn't supported
rtw_8821ce 0000:00:00.0: failed to setup chip efuse info
rtw_8821ce 0000:00:00.0: failed to setup chip information
```

**Comment by lwfinger** [comment]
Realtek has not developed c ode for rfe 4 or rfe 6. Read README.md on how to send email to the wireless  mailing list to notify them. Note: no html mail allowed on the list.

**Comment by Areidz** [comment]
Thanks. How could I contribute/help so this get fixed?

**Comment by sergiomb2** [comment]
Hello, while mainline doesn't support rfe 4 and rfe 6 . I'd like to know if this project does , it supports rfe 4 and or rfe 6 ?  I'm asking because some users ask me on https://copr.fedorainfracloud.org/coprs/sergiomb/akmod-rtl8821ce/

**Comment by lwfinger** [comment]
My project merely takes mainline code and adds the kernel version modifications necessary to build on older kernels. I do not have the knowledge to extend the drivers. Only Realtek developers have the necessary skills.

Yes, I know how to keep the driver from bailing out when an unsupported rfe version is encountered, but that will not lead to success. The behavior of the chips is different, and I have no way to know what other things have to change.

**Comment by buboleck** [comment]
Finally RFE4 support:

https://patchwork.kernel.org/project/linux-wireless/patch/20210922023637.9357-1-pkshih@realtek.com/
https://patchwork.kernel.org/project/linux-wireless/patch/20210922023637.9357-2-pkshih@realtek.com/

**Comment by flexibeast** [comment]
> Finally RFE4 support

Yay! This seems promising.

**Comment by dubhater** [comment]
> RFE type4 HW is the same as RFE type2 but attaching antenna to
> aux antenna connector.
>
> RFE type2 attach antenna to main antenna connector.

🤣🤣🤣🤣

Now the RFE 4 users can also experience the system freezes.

**Comment by flexibeast** [comment]
Applied patches to 5.13.19, seems to be working okay so far ....

**Comment by neutr0nStar** [comment]
Could anyone confirm whether Ubuntu's latest release (21.10 with kernel 5.13) has support for rtl8821ce (all RFEs) ? (Or at least RFE4)

**Comment by neutr0nStar** [comment]
> Could anyone confirm whether Ubuntu's latest release (21.10 with kernel 5.13) has support for rtl8821ce (all RFEs) ? (Or at least RFE4)

Ok, so I went ahead and dual booted my system with Ubuntu 21.10. I have RFE4 (this is what I am guessing), things worked great in the beginning, then after a few minutes, the WIFI became janky. When I try to load a page, it randomly shows No internet as if it got disconnected. Anything that I can do to improve this ?

**Comment by karimrir1** [comment]
I just found out from this bugzilla bug: https://bugzilla.kernel.org/show_bug.cgi?id=212435, that RFE4 chips not being detected was fixed in 5.16rc3. Then I found another bug report: https://bugzilla.kernel.org/show_bug.cgi?id=215131, that has a patch to solve random freezes without having to set the `disable_aspm=1` kernel parameter. I then patched my kernel, and to my surprise everything works fine.

I saw a couple of these `[  216.859364] rtw_8821ce 0000:03:00.0: failed to get tx report from firmware
[  310.691093] rtw_8821ce 0000:03:00.0: timed out to flush queue 1`
 in my dmesg after suspend, However everything seems to be fine.

**Comment by Kr1sh1** [comment]
I actually came across the freezing issue as well on fedora 34 and 35, HP 15 laptop. The disable_aspm also fixed it for me.

**Comment by karimrir1** [comment]
> I just found out from this bugzilla bug: https://bugzilla.kernel.org/show_bug.cgi?id=212435, that RFE4 chips not being detected was fixed in 5.16rc3. Then I found another bug report: https://bugzilla.kernel.org/show_bug.cgi?id=215131, that has a patch to solve random freezes without having to set the `disable_aspm=1` kernel parameter. I then patched my kernel, and to my surprise everything works fine.
> 
> I saw a couple of these `[ 216.859364] rtw_8821ce 0000:03:00.0: failed to get tx report from firmware [ 310.691093] rtw_8821ce 0000:03:00.0: timed out to flush queue 1` in my dmesg after suspend, However everything seems to be fine.

Today I started noticing these lines in my dmesg `[12770.049829] rtw_8821ce 0000:03:00.0: pci bus timeout, check dma status`, My entire dmesg was filled that I couldn't debug other issues.
The bug report https://bugzilla.kernel.org/show_bug.cgi?id=21513, that I got the patch from does mention this, However there seems to be no fix.

**Comment by buboleck** [comment]
I finally resolved all issues, replaced the card with Asus OEM spare part Atheros QCA9377 (AzureWave AW-CB231NF)

**Comment by karimrir1** [comment]
> > I just found out from this bugzilla bug: https://bugzilla.kernel.org/show_bug.cgi?id=212435, that RFE4 chips not being detected was fixed in 5.16rc3. Then I found another bug report: https://bugzilla.kernel.org/show_bug.cgi?id=215131, that has a patch to solve random freezes without having to set the `disable_aspm=1` kernel parameter. I then patched my kernel, and to my surprise everything works fine.
> > I saw a couple of these `[ 216.859364] rtw_8821ce 0000:03:00.0: failed to get tx report from firmware [ 310.691093] rtw_8821ce 0000:03:00.0: timed out to flush queue 1` in my dmesg after suspend, However everything seems to be fine.
> 
> Today I started noticing these lines in my dmesg `[12770.049829] rtw_8821ce 0000:03:00.0: pci bus timeout, check dma status`, My entire dmesg was filled that I couldn't debug other issues. The bug report https://bugzilla.kernel.org/show_bug.cgi?id=215131 that I got the patch from does mention this, However there seems to be no fix.
> 
> Edit: I also haven't experienced any freezes yet today. I will reply to this message if I experience any freezing
> 
> Edit two: While reading the kernel log from /var/log instead of dmesg, I found a couple of error messages related to pci. rtw88_8821ce has also spitted out another message that I have never seen before. `rtw_8821ce 0000:03:00.0: AER: can't recover (no error_detected callback)`. Another one, actually two related to pci is `pcieport 0000:00:1d.5: DPC: containment event, status:0x1f01 source:0x0000` `pcieport 0000:00:1d.5: DPC: unmasked uncorrectable error detected`

Experienced a freeze while writing edit three. How ironic.
