### ISSUE TITLE
Some SSID not found

### ISSUE THREAD

**Issue by mquinson** [tomaspinho/rtl8821ce#64]
Hello, 
first of all, thanks for this driver, it's really helpful as I have a network card that is not supported without it.
My problem is that while it seems to work correctly, the laptop fails to detect the set-top-box of my internet provider (```ESSID:"Freebox-58EB78"```). That's weird because the laptop detects other SSID that seem very similar, but not the one I'm interested into. Other laptops connect to this SSID with no problem.

I'm not sure about the information I should provide to help debugging the issue. Here is the output of ```iwlist wlo1 scan``` on another laptop, that do see the SSID:
```
          Cell 01 - Address: AC:E2:D3:AF:13:E6
                    Channel:6
                    Frequency:2.437 GHz (Channel 6)
                    Quality=46/70  Signal level=-64 dBm  
                    Encryption key:on
                    ESSID:"DIRECT-E5-HP OfficeJet 3830"
                    Bit Rates:6 Mb/s; 9 Mb/s; 12 Mb/s; 18 Mb/s; 24 Mb/s
                              36 Mb/s; 48 Mb/s; 54 Mb/s
                    Mode:Master
                    Extra:tsf=0000024bed51a253
                    Extra: Last beacon: 7992ms ago
                    IE: Unknown: 001B4449524543542D45352D4850204F66666963654A65742033383330
                    IE: Unknown: 01088C129824B048606C
                    IE: Unknown: 030106
                    IE: Unknown: 200100
                    IE: Unknown: 23021100
                    IE: Unknown: 2A0100
                    IE: Unknown: 2F0100
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown: 2D1A20001AFF00000000000000000000000000000000000000000000
                    IE: Unknown: 3D1606080000000000000000000000000000000000000000
                    IE: Unknown: DD090010180200000C0000
                    IE: Unknown: DD180050F202010188000364000027A4000041435E0061322F00
                    IE: Unknown: DD640800090004000000100102010003164F66666963654A657420333833302073657269657300040533383333000510434E37424534513132503036565A000006101C852A4DB8001F08ABCDACE2D3AF13E5070400000000080200C4090200080A0400000001
                    IE: Unknown: DDC40050F204104A000110104400010210570001011041000100103B000103104700101C852A4DB8001F08ABCDACE2D3AF13E5102100024850102300164F66666963654A65742033383330207365726965730010240005333833330010420010434E37424534513132503036565A00001054000800030050F20400051011001B4449524543542D45352D4850204F66666963654A657420333833301008000200001049000600372A00012010490017000137100600101C852A4DB8001F08ABCDACE2D3AF13E5
          Cell 02 - Address: E4:9E:12:DE:20:A4
                    Channel:9
                    Frequency:2.452 GHz (Channel 9)
                    Quality=44/70  Signal level=-66 dBm  
                    Encryption key:on
                    ESSID:"Freebox-58EB78"
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 22 Mb/s
                              6 Mb/s; 9 Mb/s; 12 Mb/s
                    Bit Rates:18 Mb/s; 24 Mb/s; 36 Mb/s; 48 Mb/s; 54 Mb/s
                    Mode:Master
                    Extra:tsf=000003a55aec2a71
                    Extra: Last beacon: 7948ms ago
                    IE: Unknown: 000E46726565626F782D353845423738
                    IE: Unknown: 010882848B962C0C1218
                    IE: Unknown: 030109
                    IE: Unknown: 2A0104
                    IE: Unknown: 3205243048606C
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown: 7F080000000000000040
                    IE: Unknown: DD180050F2020101000003A4000027A4000042435E0062322F00
                    IE: Unknown: DD0C0007CB010101000000000000
```

Here is the full output of the same command on the machine using the  rlt8821ce network card:
```
wlp2s0    Scan completed :
          Cell 01 - Address: AC:E2:D3:AF:13:E6
                    ESSID:"DIRECT-E5-HP OfficeJet 3830"
                    Protocol:IEEE 802.11gn
                    Mode:Master
                    Frequency:2.437 GHz (Channel 6)
                    Encryption key:on
                    Bit Rates:72 Mb/s
                    Extra:rsn_ie=30140100000fac040100000fac040100000fac020c00
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown: DDC40050F204104A000110104400010210570001011041000100103B000103104700101C852A4DB8001F08ABCDACE2D3AF13E5102100024850102300164F66666963654A65742033383330207365726965730010240005333833330010420010434E37424534513132503036565A00001054000800030050F20400051011001B4449524543542D45352D4850204F66666963654A657420333833301008000200001049000600372A00012010490017000137100600101C852A4DB8001F08ABCDACE2D3AF13E5
                    Quality=85/100  Signal level=-68 dBm  
                    Extra:fm=0003
          Cell 02 - Address: B0:B2:8F:99:EC:50
                    ESSID:"Livebox-EC50"
                    Protocol:IEEE 802.11bgn
                    Mode:Master
                    Frequency:2.412 GHz (Channel 1)
                    Encryption key:on
                    Bit Rates:144 Mb/s
                    Extra:rsn_ie=30140100000fac040100000fac040100000fac020c00
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown: DD970050F204104A0001101044000102103B00010310470010423042323846F939F54335304230423210210008536167656D636F6D10230015536167656D636F6D46617374353336305F4D4942341024000C53475F4C42345F312E312E30104200094E51313631383546461054000800060050F2040001101100094C697665626F782034100800020001103C0001011049000600372A000120
                    Quality=78/100  Signal level=-91 dBm  
                    Extra:fm=0003
          Cell 03 - Address: B0:B2:8F:99:EC:51
                    ESSID:"orange"
                    Protocol:IEEE 802.11bgn
                    Mode:Master
                    Frequency:2.412 GHz (Channel 1)
                    Encryption key:off
                    Bit Rates:144 Mb/s
                    Quality=88/100  Signal level=-90 dBm  
                    Extra:fm=0003
          Cell 04 - Address: FA:8F:CA:52:D3:97
                    ESSID:"Cuisine.o"
                    Protocol:IEEE 802.11bgn
                    Mode:Master
                    Frequency:2.437 GHz (Channel 6)
                    Encryption key:off
                    Bit Rates:72 Mb/s
                    Quality=54/100  Signal level=-89 dBm  
                    Extra:fm=0003
          Cell 05 - Address: 40:65:A3:FC:7D:B2
                    ESSID:"Livebox-7DB2"
                    Protocol:IEEE 802.11bgn
                    Mode:Master
                    Frequency:2.437 GHz (Channel 6)
                    Encryption key:on
                    Bit Rates:144 Mb/s
                    Extra:wpa_ie=dd1a0050f20101000050f20202000050f2040050f20201000050f202
                    IE: WPA Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : CCMP TKIP
                        Authentication Suites (1) : PSK
                    Extra:
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : CCMP TKIP
                        Authentication Suites (1) : PSK
                    IE: Unknown: DD8F0050F204104A0001101044000102103B000103104700103B373D3C483AFD4AFE4B49393B373D3C10210008536167656D636F6D10230016536167656D636F6D46617374333936355F4C42322E381024000C53475F4C42335F312E322E31104200093332313631373446461054000800060050F204000110110000100800020006103C0001011049000600372A000120
                    Quality=26/100  Signal level=-91 dBm  
                    Extra:fm=0003
          Cell 06 - Address: 12:65:A3:FC:7D:B2
                    ESSID:"orange"
                    Protocol:IEEE 802.11bgn
                    Mode:Master
                    Frequency:2.437 GHz (Channel 6)
                    Encryption key:off
                    Bit Rates:144 Mb/s
                    Quality=54/100  Signal level=-93 dBm  
                    Extra:fm=0003
          Cell 07 - Address: 54:64:D9:3B:F2:C4
                    ESSID:"Livebox-F2C4"
                    Protocol:IEEE 802.11bgn
                    Mode:Master
                    Frequency:2.437 GHz (Channel 6)
                    Encryption key:on
                    Bit Rates:144 Mb/s
                    Extra:wpa_ie=dd1a0050f20101000050f20202000050f2040050f20201000050f202
                    IE: WPA Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : CCMP TKIP
                        Authentication Suites (1) : PSK
                    Extra:
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : CCMP TKIP
                        Authentication Suites (1) : PSK
                    IE: Unknown: DD1D0050F204104A0001101044000102103C0001011049000600372A000120
                    Quality=4/100  Signal level=-94 dBm  
                    Extra:fm=0001
          Cell 08 - Address: A0:63:91:C7:B3:B3
                    ESSID:"Livebox-E1D4_2GEXT"
                    Protocol:IEEE 802.11bgn
                    Mode:Master
                    Frequency:2.462 GHz (Channel 11)
                    Encryption key:on
                    Bit Rates:144 Mb/s
                    Extra:wpa_ie=dd1a0050f20101000050f20202000050f2020050f20401000050f202
                    IE: WPA Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : TKIP CCMP
                        Authentication Suites (1) : PSK
                    Extra:
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : TKIP CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown: DD880050F204104A0001101044000102103B00010310470010D9F83E06A24D80083EBA385C37394A6A1021000D4E4554474541522C20496E632E10230006455833383030102400064558333830301042000D343756323535374E41323538311054000800060050F20400011011000645583338303010080002218C103C0001011049000600372A000120
                    Quality=69/100  Signal level=-90 dBm  
                    Extra:fm=0003

```

I'm really puzzled because the rtl card sees the same Cell 01 than the working one, but not the Cell 02. I fail to see any change between the machines that may explain this.

I understand that you don't have a RTL8821CE card anymore and that you cannot really help me here, but I'd be really grateful for any help you could provide.

Thanks,

**Comment by lindquistc** [comment]
Hello Martin, I had the same issue as you reported: my laptop (running Ubuntu 19.04) wireless card (rtl8821ce) apparently worked with the current version of this driver (latest commit, August 16), i.e. it detected most of the SSIDs of my neighborhood. Unfortunately (and quite strangely) it could not detect the wifi signal from my Freebox, which could be detected by my smartphone, another laptop, etc. The solution for me was to use an older version, I chose commit 6fcab13 of March 1 (Fix compilation against Linux 5.0.0) since my Kernel version is 5.0.0. Now it works like a charm! I hope this helps you while waiting for a fix.

**Comment by aquaris45** [comment]
hello, 
i have exactly same behaviour today with driver version kernel: [ 1637.953641] RTW: rtl8821ce v5.5.2_34066.20190614_COEX20180712-3232
freebox wifi network is not detected.
i have compiled the same old version 6fcab13 and ... tada ... my freebox wifi is seen and usable.
i don't have enough knowledge to analyse this trouble but using the old version is a workable circumvention.

**Comment by mquinson** [comment]
I bisected the problem. 
It works with https://github.com/tomaspinho/rtl8821ce/commit/62742760ce5029e52c197632d641fe5c40a06db7 which is a bit later than the previously know working commit, but not in https://github.com/tomaspinho/rtl8821ce/commit/6b9a569657afb530020c3489ff88886ad7b157ce so the problem lays in #54. Since I failed to compile the individual commits of that PR, and since I don't understand the code, there is not much I can do here.

Note that it also doesn't work with the current latest commit, https://github.com/tomaspinho/rtl8821ce/commit/55b90f46e203c6f46f731b039497b9aac8ea67ac .

I hope that this information helps someone with better technical habilities. I'm available to run all tests you want if it can help.

Thanks for the fish,

**Comment by farid4212** [comment]
Sam problème some ssid not fond
In kernel >5.3.6

**Comment by Fivizzz** [comment]
Same ISP, same issue. Had to use [6fcab13](https://github.com/tomaspinho/rtl8821ce/commit/6fcab13542e797816ced44184eb6d0976fbb8683) as well to work around it.

Am using Mini 4K router, don't know if the problem appears with all of Free's hardware but they must be doing something different with their WiFi signal. Tried multiple options in router wifi config none of which made the SSID visible by the recent commits.

**Comment by brubar** [comment]
FWIW: same ISP, same issue here too. I've checked out 6274276 and installed it. I'm now seeing Freebox ESSIDs, and I'm connected to mine.
```
Linux 5.0.0-29-generic #31~18.04.1-Ubuntu SMP x86_64
```
@mquinson: Thanks for bisecting a working commit

And thanks Tomás for your work on this driver.

I may provide some help testing, but only for a short period, as I don't own that laptop.

**Comment by Topper30** [comment]
Same ISP here, same device (Freebox), but no SSID shown with #6fcab13

`Linux 5.3.6-arch1-1-ARCH x86_64`

Thanks to work on this !

**Comment by Funeoz** [comment]
I also have a Freebox. I tried to compile the module from the latest commit on Kubuntu 19.10 (kernel : 5.3.0.18.21). Got some errors so I didn't try to go further. So as a workaround, I'm booting Kubuntu with an older kernel and a older module compiled.

**Comment by Funeoz** [comment]
@mquinson Which kernel are you using ?

**Comment by mquinson** [comment]
```
$ uname -a
Linux host 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Jodaille** [comment]
Hi,
driver works with an Openwrt router, but cannot see Freebox SSID.
Kernel 5.3.0-8.1-liquorix-amd64 on Debian Buster

**Comment by xbeaudet** [comment]
Hi,
quite same problem here, but i can precise it a little (and workaround inside) :
on a freebox revolution, only ssid on 2.4Ghz card are not seen. 
When i activate the 5Ghz card of the box, my laptop sees the SSID affected to the card (i choose to set a different SSID for the 2 frequencies, only the 5Ghz one is detected and works when connected to).
This still is a problem for some access points....

using a manjaro linux, kernel 5.3.11-1, i tried the 16  last commits with no success for 2.4Ghz (1ddc1d901ea5157b008c6262e4b2a03f0fadf228 to 697c5abe9b3c7bff67153770485463162806b288)

ended with using AUR version on 5Ghz SSID which is ok at home, but only at home : i will have problems in some places where i won't be able to connect...

**Comment by soladev** [comment]
I have the same problem, with that same ISP

**Comment by lindquistc** [comment]
As explained in my [previous post](https://github.com/tomaspinho/rtl8821ce/issues/64#issuecomment-523655960), I managed to use my laptop's RTL8821CE wireless card and to see my Freebox SSID after installing version [6fcab13](https://github.com/tomaspinho/rtl8821ce/commit/6fcab13542e797816ced44184eb6d0976fbb8683) of this driver on a laptop running Ubuntu 19.04 (kernel 5.0.0). 

Today, after upgrading Ubuntu to version 19.10 (kernel 5.3.0-24-generic), the wireless card was not working anymore... Looking (again) for a solution to this problem, I've found a [package](https://packages.ubuntu.com/en/eoan/all/rtl8821ce-dkms) in the universe repository of Ubuntu 19.10 containing a driver for the RTL8821CE wireless card. After removing the old driver (`sudo ./dkms-remove.sh` from the folder containing the source downloaded from GitHub) and installing the above mentioned package (`sudo apt-get install rtl8821ce-dkms`), the wireless card worked again and I can now use my Freebox SSID!

**Comment by Fivizzz** [comment]
Oh interesting, so Realtek's drivers have indeed been implemented in Ubuntu 19.10. I've been holding off on upgrading because of reported issues with Kernel ver 5.3.xxx. Will try it out next weekend and report.

**Comment by Funeoz** [comment]
I can also confirm that the wifi works for the Kernel 5.3.0-24-generic with the package ```rtl8821ce-dkms``` and the Freebox.

**Comment by delestro** [comment]
Thank you so much for this thread, I also confirm that `sudo apt-get install rtl8821ce-dkms` solves the problem for Ubuntu 19.10, running on a Lenovo Ideapad S540 with a RTL8821CE 802.11ac PCIe Wireless.

Before I could detect some networks, but not the one from Freebox. Everything is fine now

**Comment by Fivizzz** [comment]
Note: For people now running the `rtl8821ce-dkms` package on Ubuntu 19.10, the package has recently been updated, and Freebox SSID have disappeared again (after full reboot and not after update and module restart, mind you).

Apparently `rtl8821ce-dkms` is based on this driver and our issue has finally made it into the official repos :D

Reverting package to previous version solves it. 
`sudo apt-get install rtl8821ce-dkms=5.2.5.2.1.30816.20190425-0ubuntu1`

You might wanna hold the version from future updates as well after that.
`sudo apt-mark hold rtl8821ce-dkms`

**Comment by Funeoz** [comment]
That will be an issue for the next upgrade to Ubuntu Eoan. The package is based on the version ```5.5.2.1-0ubuntu3```...

**Comment by Funeoz** [comment]
I've started a new thread about this bug on launchpad:
https://bugs.launchpad.net/ubuntu/+source/rtl8821ce/+bug/1865147

**Comment by Fivizzz** [comment]
Thanks. Everyone in this thread should mark themselves as affected in Funeoz's launchpad thread to give the bug visibility and hopefully get some able stranger to fix it before 20.04.

**Comment by aauzi** [comment]
> As explained in my [previous post](https://github.com/tomaspinho/rtl8821ce/issues/64#issuecomment-523655960), I managed to use my laptop's RTL8821CE wireless card and to see my Freebox SSID after installing version [6fcab13](https://github.com/tomaspinho/rtl8821ce/commit/6fcab13542e797816ced44184eb6d0976fbb8683) of this driver on a laptop running Ubuntu 19.04 (kernel 5.0.0).
> 
hi everyone,
I was facing the same issue plus a kernel error on kernel 5.5.8 on Fedora 31.
Based on the information above I managed to build a workaround that gives me back the freebox SSIDs.
One can check it out in [the workaround-freebox branch of my fork](https://github.com/aauzi/rtl8821ce/tree/workaround-freebox).

**Comment by Funeoz** [comment]
If this works, maybe you could ask for a PR on this repo.

**Comment by healBvdb** [comment]
Thanks aauzi for your workaround I did succeed to get my Freebox SSID with it. Otherwise I could not get it on a laptop running Ubuntu 19.10

**Comment by tomaspinho** [comment]
We have a fix in https://github.com/tomaspinho/rtl8821ce/pull/135 that you can try out in the meantime, thanks to @BuBuaBu

**Comment by ludzovic** [comment]
> We have a fix in #135 that you can try out in the meantime, thanks to @BuBuaBu

This worked perfectly for me, thanks a lot! I'm on Kubuntu 19.10, kernel 5.3.0-45. Laptop FX505DT

**Comment by tomaspinho** [comment]
Fix now merged into master. Closing this issue. Thanks everyone!

**Comment by Funeoz** [comment]
Just to say that the fix has been merged for the packaged version `rtl8821ce-dkms`. Not tested yet but it should be working. https://bugs.launchpad.net/ubuntu/+source/rtl8821ce/+bug/1865147

**Comment by Funeoz** [comment]
The fix has also been released for the Ubuntu package `rtl8821ce-dkms`.

**Comment by afgranero** [comment]
I still have the problem on an HP256 G8 on a Linux Mint Uma. 
I tried the Ubuntu package and compiling from this source in master and all branches discussed here.
I have an TL-WR941ND running a custom version of DD-WRT for this exact model. I have more than 15 devices connected from several brands, some of them running Linux Mint Uma, so I don't think is a router problem per se.
I thought it was the regulatory domain that blocks some channels in my country, but it was not the case. I even changed the channel for one that I was sure is not forbidden with no result. My router off course broadcasts the SSID and my SSID has no special chars on it, so I think it is really an issue.
